"""
python OpenSSL bindings have problems parsing Bloomberg (and some other) OIDs in the Subject
field. Without doing the ASN.1 parsing ourselves all we get in the Subject field of some
certificates is 'Undef'

This is the work around that parses the ASN.1 and gives a list of OIDs that can later be
resolved to readable text.
"""

# -------------------------------------------------#
# DO NOT EDIT BELOW                                #
# autogenerated from ASN.1 source by a ASN.1 parser#
# X.509 spec (rfc2459)                             #
# -------------------------------------------------#

from Imports import *

__id__ = "$Id: X509ASN1.py 57 2014-03-19 03:26:46Z user $"

MAX = 64

class DirectoryString(univ.Choice):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('teletexString', char.TeletexString().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, MAX))),
        namedtype.NamedType('printableString', char.PrintableString().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, MAX))),
        namedtype.NamedType('universalString', char.UniversalString().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, MAX))),
        namedtype.NamedType('utf8String', char.UTF8String().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, MAX))),
        namedtype.NamedType('bmpString', char.BMPString().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, MAX))),
        namedtype.NamedType('ia5String', char.IA5String().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, MAX))) # hm, this should not be here!? XXX
        )

class AttributeValue(DirectoryString): pass

class AttributeType(univ.ObjectIdentifier): pass

class AttributeTypeAndValue(univ.Sequence):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('type', AttributeType()),
        namedtype.NamedType('value', AttributeValue())
        )

class RelativeDistinguishedName(univ.SetOf):
    componentType = AttributeTypeAndValue()

class RDNSequence(univ.SequenceOf):
    componentType = RelativeDistinguishedName()

class Name(univ.Choice):
    componentType = namedtype.NamedTypes(
        namedtype.NamedType('', RDNSequence())
        )
# -------------------------------------------------#
# DONE DO NOT EDIT SECTION                         #
# end autogenerated ASN.1 code                     #
# X.509 spec (rfc2459)                             #
# -------------------------------------------------#